template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "arom1237"
__REPO__ = "lang-rup"
__UND2C__ = "rup"
__UNDEFINED__ = "Macedo-Romanian"
__UND__ = "rup"
