template = "https://github.com/giellalt/template-lang-und"
rev_id = 327
template_sha = "65f0d288ed0f81badfaa2043de3fd624c73adb20"

[replacements]
__GLOTTOLOG_ID__ = "arom1237"
__REPO__ = "lang-rup"
__UND2C__ = "rup"
__UNDEFINED__ = "Macedo-Romanian"
__UND__ = "rup"
