template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "arom1237"
__REPO__ = "lang-rup"
__UND2C__ = "rup"
__UNDEFINED__ = "Macedo-Romanian"
__UND__ = "rup"
