[package]
name = "rup"
human_name = "Macedo-Romanian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.rup]
filename = "rup-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-rup"
platform = "windows"
uuid = "B6FD06A8-2448-4A35-AF3F-698D82DA6777"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.rup"
package = "speller-rup"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-rup-mso"
platform = "windows"
uuid = "6C450BEB-4EB7-49F6-99ED-0B46CA269E6B"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-rup"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
